config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'overviews#index'
  resources :overviews do    
    member do
      get 'physicalfinding'
      get 'bloodurine'
      get 'medicalcare'
      get 'vaccine'
    end

    collection do
      get 'new_physicalfinding'
      get 'new_bloodurine'
      get 'new_medicalcare'
      get 'new_vaccine'
    end
    
  end
end

app/controllers/overviews_controller.rb
class OverviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :physicalfinding, :bloodurine, :medicalcare, :vaccine]
  before_action :move_to_index, except: [:index]
  before_action :set_overview, only: [:edit, :update, :destroy]
  before_action :set_chart, only: [:index, :physicalfinding]
  before_action :overview_physicalfinding_measuring, only: [:index, :physicalfinding]
  before_action :overview_blood_urine_test, only: [:index, :bloodurine]
  before_action :overview_medical_care, only: [:index, :medicalcare]
  before_action :overview_vaccines, only: [:index, :vaccine]

  def index
  end

  def new
    @overview = Overview.new
  end

  def new_physicalfinding
    @overview = Overview.new
  end

  def new_bloodurine
    @overview = Overview.new
  end

  def new_medicalcare
    @overview = Overview.new
  end
  def new_vaccine
    @overview = Overview.new
  end

  def create
    @overview = Overview.create(overview_params)
    if @overview.valid?
      @overview.save
      redirect_to root_path
    else
      render new_overview_path
    end
  end

  def edit
    unless current_user == @overview.user
      redirect_to root_path
    end
  end

  def update
    if @overview.update(overview_params)
      @overview.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @overview.destroy
    if @overview.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def physicalfinding
  end

  def bloodurine
  end

  def medicalcare
  end

  def vaccine
  end

  private

  def overview_params
    params.require(:overview).permit(:physicalfinding_measuring_date, :weight, :height, :abdominal_circumference,:bmi, :blood_urine_test_date, :image,:medical_care_date, :clinic_name, :disease_name, :treatment_medicine, :vaccine_date, :vaccine_id).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def set_overview
    @overview = Overview.includes(:user).find(params[:id])
  end

  def set_chart
    if user_signed_in?
      physicalfinding_measuring_date = Overview.where.not(physicalfinding_measuring_date:nil).where(user_id: current_user.id).order(physicalfinding_measuring_date: :asc).pluck(:physicalfinding_measuring_date)
      weight = Overview.where.not(physicalfinding_measuring_date:nil).where(user_id: current_user.id).order(physicalfinding_measuring_date: :asc).pluck(:weight)
      bmi = Overview.where.not(physicalfinding_measuring_date:nil).where(user_id: current_user.id).order(physicalfinding_measuring_date: :asc).pluck(:bmi)
      abdominal_circumference = Overview.where.not(physicalfinding_measuring_date:nil).where(user_id: current_user.id).order(physicalfinding_measuring_date: :asc).pluck(:abdominal_circumference)

      @chart = LazyHighCharts::HighChart.new("graph") do |c|
        # c.title(text: "体重・腹囲 推移")
        c.xAxis(categories: physicalfinding_measuring_date)
        c.yAxis(title: {text: 'kg / cm'})
        c.series(name: "腹囲 cm", data: abdominal_circumference)
        c.series(name: "体重 kg", data: weight)
        c.series(name: "BMI", data: bmi)
      end
    end
  end

  def overview_physicalfinding_measuring
    @overview_physicalfinding_measurings = Overview.includes(:user).where.not(physicalfinding_measuring_date:nil).order(physicalfinding_measuring_date: :desc).where(params[:id])
  end

  def overview_blood_urine_test
    @overview_blood_urine_tests = Overview.includes(:user).where.not(blood_urine_test_date:nil).order(blood_urine_test_date: :desc).where(params[:id])
  end

  def overview_medical_care
    @overview_medical_cares = Overview.includes(:user).where.not(medical_care_date:nil).order(medical_care_date: :desc).where(params[:id])
  end

  def overview_vaccines
    @overview_vaccines = Overview.includes(:user).where.not(vaccine_date:nil).order(vaccine_date: :desc).where(params[:id])
  end

end

app/helpers/overviews_helper.rb
module OverviewsHelper
end

app/views/overviews/bloodurine.html.erb
<div  id="page-top">

<% if user_signed_in? %>
    <!-- Page Wrapper -->
    <div id="wrapper">

     <!-- Content Wrapper -->
     <div id="content-wrapper" class="d-flex flex-column">

         <!-- Main Content -->
         <div id="content">
            <%= render "shared/header" %>

            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- Earnings (Monthly) Card Example -->
                <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">採血・採尿・画像検査</h3>
                </div>
                <div class="card-body">
                    <% if @overview_blood_urine_tests.where.not(blood_urine_test_date:nil).where(user_id: current_user.id).present? %>
                           
                    <% @overview_blood_urine_tests.each do |overview| %>
                                <% if current_user.id == overview.user_id %>
                                    <div class="font-weight-bold text-uppercase mt-2 mb-2">
                                            測定日 <%= overview.blood_urine_test_date %>
                                            <%= link_to edit_overview_path(overview.id), method: :get do%>
                                                <div class="btn btn-info btn-circle btn-sm"><i class="far fa-edit"></i></div>
                                                <div class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash btn-sm"></i></div>
                                            <% end %>
                                    </div>
                                    <span class="h5 mb-0 font-weight-bold text-gray-800 mr-5">
                                        <%= image_tag overview.image, class: 'test-image' if overview.image.present?  %>                                                                           
                                    </span>
                                    <hr class="sidebar-divider">
                                <% end %>
                            <% end %>
                    <% else %>
                        <p class="h6 font-weight-bold text-uppercase mb-1 mr-2">
                        データを登録してね！
                        </p>
                    <% end %>
                </div>
            </div>     
    </div>
<% end %>
    <!-- End of Main Content -->

<%= render "shared/fotter" %>

app/views/overviews/edit.html.erb
<div  id="page-top">
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
        <div id="content">

          <%= render "shared/header" %>

            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="p-5 pt-3">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                  <h1 class="h3 mb-0 text-gray-800">編集・削除</h1>
                </div>

                  <%= form_with model: @overview, class: 'user',name: 'form', local: true do |f| %> 
                    <%= render 'shared/error_messages', model: f.object %>
                  
                  <div class="card card-body border-left-success mb-3 py-3">
                    <div class="h5 m-3">
                      身長・体重・腹囲
                    </div>
                    <div class="form-group ml-4">
                        <div class='input-date-wrap'>
                          <label class="col-sm-12 col-md-2">測定日</label>
                          <%= raw sprintf(
                                        f.date_select(
                                          :physicalfinding_measuring_date,
                                          use_month_numbers: true,
                                          prompt:'--',
                                          start_year: (Time.now.year),
                                          end_year: 2000,
                                          date_separator: '%s'),
                                        "<p> 年 </p>", "<p> 月 </p>",) + "<p> 日 </p>" %>
                        </div>                                
                        <div class="row">
                          <div class="col-md-6 mt-2">
                            <%= f.text_field :height, class:"input-default form-control form-control-user overview", id:"height", placeholder:"身長（半角）cm", maxlength:"3" %> 
                          </div>                             
                          <div class="col-md-6 mt-2">
                            <%= f.text_field :weight, class:"input-default form-control form-control-user overview", id:"weight", placeholder:"体重（半角）cm", maxlength:"3" %>  
                          </div>
                          <div class="col-md-6 mt-2">
                            <%= f.text_field :abdominal_circumference, class:"input-default form-control form-control-user overview", id:"abdominal_cicumference", placeholder:"腹囲（半角）cm", maxlength:"3" %>
                          </div>
                          <div class="col-md-6 mt-2" >
                            <%= f.text_field :bmi, class:"input-default form-control form-control-user overview", id:"bmi-form", placeholder:"BMI 自動で計算されます", maxlength:"3" %>
                          </div>
                        </div>
                    </div>
                  </div>

                  <div class="card card-body border-left-info mb-3 py-3">
                    <div class="h5 m-3">
                    採血・採尿
                    </div>
                    <div class="form-group ml-4">
                        <div class='input-date-wrap'>
                          <label class="col-sm-12 col-md-2">測定日</label>
                          <%= raw sprintf(
                                        f.date_select(
                                          :blood_urine_test_date,
                                          use_month_numbers: true,
                                          prompt:'--',
                                          start_year: (Time.now.year),
                                          end_year: 2000,
                                          date_separator: '%s'),
                                        "<p> 年 </p>", "<p> 月 </p>",) + "<p> 日 </p>" %>
                        </div>                                 
                        
                        <div class="btn btn-light btn-icon-split mt-2 blood-urine-test"> 
                          <label class="text">画像を選択
                            <%= f.file_field :image, accept: '.jpeg, .jpg, .gif, .png, .bmp', style:"display:none", id:"item-image"  %>
                          </label>
                        </div>
                          
                        <div id="image-list">
                          <%= image_tag @overview.image, id: 'image' if @overview.image.present? %> 
                        </div>

                    </div>
                  </div>

                  <div class="card card-body border-left-warning mb-3 py-3">
                    <div class="h5 m-3">
                    受診歴
                    </div>
                    <div class="form-group ml-4">
                        <div class='input-date-wrap'>
                          <label class="col-sm-12 col-md-2">受診日</label>
                          <%= raw sprintf(
                                        f.date_select(
                                          :medical_care_date,
                                          use_month_numbers: true,
                                          prompt:'--',
                                          start_year: (Time.now.year),
                                          end_year: 2000,
                                          date_separator: '%s'),
                                        "<p> 年 </p>", "<p> 月 </p>",) + "<p> 日 </p>" %>
                        </div>                                
                        <div class="row">
                          <div class="col-12 mt-2">
                            <%= f.text_field :clinic_name, class:"input-default form-control form-control-user overview-medical-care", id:"clinic_name", placeholder:"病院名(◯◯クリニックなど)", maxlength:"40" %> 
                          </div>                             
                          <div class="col-12 mt-2">
                            <%= f.text_field :disease_name, class:"input-default form-control form-control-user overview-medical-care", id:"disease_name", placeholder:"病名(胃ポリープ、膀胱炎など)", maxlength:"60" %>  
                          </div>
                          <div class="col-12 mt-2">
                            <%= f.text_field :treatment_medicine, class:"input-default form-control form-control-user overview-medical-care", id:"treatment_medicine", placeholder:"処置・薬(内視鏡、抗生剤 服用など)", maxlength:"60" %>  
                          </div>
                        </div>
                    </div>
                  </div>

                  <div class="card card-body border-left-danger mb-3 py-3">
                    <div class="h5 m-3">
                    ワクチン接種歴
                    </div>
                    <div class="form-group ml-4">
                        <div class='input-date-wrap'>
                          <label class="col-sm-12 col-md-2">接種日</label>
                          <%= raw sprintf(
                                        f.date_select(
                                          :vaccine_date,
                                          use_month_numbers: true,
                                          prompt:'--',
                                          start_year: (Time.now.year),
                                          end_year: 2000,
                                          date_separator: '%s'),
                                        "<p> 年 </p>", "<p> 月 </p>",) + "<p> 日 </p>" %>
                        </div>                                
                            <%= f.collection_select(:vaccine_id, Vaccine.all, :id, :name, {}, {class:"mt-3 overview"}) %>
                        </div>
                    </div>
                  </div>
                      <%= f.submit "再登録" ,class:"btn btn-facebook btn-block" ,id:"registration" %>
                      <%= link_to "削除", overview_path(@overview.id), method: :delete, class: 'btn btn-google btn-block' %>
                  <% end %>
              </div>         
            </div>
<%= render "shared/fotter" %>

app/views/overviews/index.html.erb
<% unless user_signed_in? %>
    <div class="bg-gradient-primary">
       <div class="container">
           <!-- Outer Row -->
           <div class="row justify-content-center">
               <div class="col-xl-10 col-lg-12 col-md-9">
                   <div class="card o-hidden border-0 shadow-lg my-5">
                       <div class="card-body p-0">
                           <!-- Nested Row within Card Body -->
                           <div class="row">
                               <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                               <div class="col-lg-6">
                                   <div class="p-5">
                                       <div class="text-center">
                                           <h1 class="h4 text-gray-900 mb-4">HealthCode</h1>
                                           <p class="mb-4">自分の身体は自分で管理を</p>
                                           <p class="mb-4">検診結果、薬歴などをデータ管理しましょう。</p>
                                       </div>
                                       <hr>
                                       <div class="text-center mb-4">
                                           <%= link_to 'ログイン', new_user_session_path%>
                                       </div>
                                       <div class="text-center">
                                            <%= link_to '新規登録', new_user_registration_path %>
                                       </div>
                                   </div>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
    </div>
<% end %>

<% if user_signed_in? %>
<!-- Page Wrapper -->
    <div id="wrapper">

    <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <%= render "shared/header" %>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">最新情報</h1>
                    </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="card border-left-success shadow h-100 py-2 md-12 mb-4">
                            <div class="card-body">
                                <span class="h5 font-weight-bold text-uppercase mb-1 mr-2">
                                        体重・腹囲・BMI
                                </span>
                                <% if @overview_physicalfinding_measurings.where(user_id: current_user.id).present? %>
                                    <div class="mt-3">
                                        <%= high_chart("my_chart", @chart) %>
                                    </div>
                                <% else %>
                                    <p class="h6 font-weight-bold text-uppercase mb-1 mr-2">
                                    データを登録してね！
                                    </p>
                                <% end %> 
                            </div>
                        </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="card border-left-info shadow h-100 py-2 md-12 mb-4">
                            <div class="card-body">
                                <span class="h5 font-weight-bold text-uppercase mb-1 mr-2">
                                    採血・採尿
                                </span>
                                <% if @overview_blood_urine_tests.where(user_id: current_user.id).present? %>
                                    <div class="font-weight-bold text-uppercase mt-2 mb-2">
                                            最新測定日 <%= @overview_blood_urine_tests.where(user_id: current_user.id).first.blood_urine_test_date %>
                                            <%= link_to edit_overview_path(@overview_blood_urine_tests.where(user_id: current_user.id).first.id), method: :get do%>
                                                <div class="btn btn-info btn-circle btn-sm"><i class="far fa-edit"></i></div>
                                                <div class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash btn-sm"></i></div>
                                            <% end %>
                                    </div>
                                    
                                    <span class="h5 mb-0 font-weight-bold text-gray-800 mr-5">
                                        <%= image_tag @overview_blood_urine_tests.where(user_id: current_user.id).first.image, class: 'test-image' if @overview_blood_urine_tests.where(user_id: current_user.id).first.image.present? %>                                         
                                    </span>
                                <% else %>
                                    <p class="h6 font-weight-bold text-uppercase mb-1 mr-2">
                                        データを登録してね！
                                    </p>
                                <% end %>
                            </div>
                        </div>            
                            
                    <!-- Earnings (Monthly) Card Example -->
                    <div class="card border-left-warning shadow h-100 py-2 md-12 mb-4">
                        <div class="card-body">
                            <span class="h5 font-weight-bold text-uppercase mb-2">
                                最終受診歴
                            </span>
                            <% if @overview_medical_cares.where(user_id: current_user.id).present? %>
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr class="thead bg-primary bg-gradient text-light">
                                                <th></th>
                                                <th>病院名</th>
                                                <th>病名・診断名</th>
                                                <th>処置・薬</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <% @overview_medical_cares.first(3).each do |overview_medical_care| %>
                                                <tr>
                                                    <td><%= overview_medical_care.medical_care_date %></td>
                                                    <td data-label="病院名"><%= overview_medical_care.clinic_name %></td>
                                                    <td data-label="病名"><%= overview_medical_care.disease_name %></td>
                                                    <td data-label="処置・薬"><%= overview_medical_care.treatment_medicine %></td>
                                                    <td>  
                                                    <%= link_to edit_overview_path(overview_medical_care.id), method: :get do%>
                                                        <div class="btn btn-info btn-circle btn-sm"><i class="far fa-edit"></i></div>
                                                        <div class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash btn-sm"></i></div>
                                                    <% end %>
                                                    </td>
                                                </tr> 
                                            <% end %>
                                        </tbody>
                                    </table>
                                </div>
                            <% else %>
                                <p class="h6 font-weight-bold text-uppercase mb-1 mr-2">
                                    データを登録してね！
                                </p>    
                            <% end %> 
                        </div>
                    </div>
    
                    <!-- Earnings (Monthly) Card Example -->
                    <div class="card border-left-danger shadow h-100 py-2 md-12 mb-4">
                        <div class="card-body">
                            <span class="h5 font-weight-bold text-uppercase mb-1 mr-2">
                                最終ワクチン接種歴
                            </span>
                            <% if @overview_vaccines.where(user_id: current_user.id).present? %>
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                            <tr class="thead bg-primary bg-gradient text-light">
                                                <th>接種日</th>
                                                <th>種類</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <% @overview_vaccines.first(3).each do |overview_vaccine| %>
                                                <tr>
                                                    <td><%= overview_vaccine.vaccine_date %></td>
                                                    <td data-label="種類"><%= overview_vaccine.vaccine.name %></td>
                                                    <td>
                                                    <%= link_to edit_overview_path(overview_vaccine.id), method: :get do%>
                                                        <div class="btn btn-info btn-circle btn-sm"><i class="far fa-edit"></i></div>
                                                        <div class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash btn-sm"></i></div>
                                                    <% end %>
                                                </td>
                                                </tr>
                                            <% end %>
                                        </tbody>
                                    </table>
                                </div>
                            <% else %>
                                <p class="h6 font-weight-bold text-uppercase mb-1 mr-2">
                                    データを登録してね！
                                </p>      
                            <% end %>
                        </div>     
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <% end %>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

app/views/overviews/new_bloodurine.erb
<div  id="page-top">
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
        <div id="content">

          <%= render "shared/header" %>

            <!-- Nested Row within Card Body -->


                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                  <h1 class="h4 mb-0 text-gray-800 ml-3">採血・採尿・画像検査</h1>
                </div>

                  <%= form_with model: @overview, url: overviews_path, class: 'user',name: 'form', local: true do |f| %> 
                    
                    <%= render 'shared/error_messages', model: f.object %>
                    <div class="form-group ml-4">
                        <div class='input-date-wrap'>
                          <label>測定日</label>
                          <%= raw sprintf(
                                        f.date_select(
                                          :blood_urine_test_date,
                                          use_month_numbers: true,
                                          prompt:'--',
                                          start_year: (Time.now.year),
                                          end_year: 2000,
                                          date_separator: '%s'),
                                        "<p> 年 </p>", "<p> 月 </p>",) + "<p> 日 </p>" %>
                        </div>                                 
                        
                        <div class="btn btn-light btn-icon-split mt-2 blood-urine-test"> 
                          <label class="text">画像を選択
                            <%= f.file_field :image, accept: '.jpeg, .jpg, .gif, .png, .bmp', style:"display:none", id:"item-image" %>
                          </label>
                        </div>
                    </div>

                    <div id="image-list">
                      <%= image_tag @overview.image, id: 'image' if @overview.image.present? %> 
                    </div>

                      <%= f.submit "登録" ,class:"btn btn-facebook btn-block" ,id:"registration" %>
                  <% end %>


<%= render "shared/fotter" %>