config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'overviews#index'
  resources :overviews do    
    member do
      get 'physicalfinding'
      get 'bloodurine'
      get 'medicalcare'
      get 'vaccine'
    end

    collection do
      get 'new_physicalfinding'
      get 'new_bloodurine'
      get 'new_medicalcare'
      get 'new_vaccine'
    end
    
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>

<!-- Begin Page Content -->
  <div class="container-fluid">

    <!-- 404 Error Text -->
     <div class="text-center">
      <div class="error mx-auto">Error</div>
        <p class="lead text-gray-800 mb-5">
        <% model.errors.full_messages.each do |message| %>
        </p>
        <p>
        <%= message %>
        </p>
      <% end %>
    </div>

   <!-- /.container-fluid -->

   </div>
   <!-- End of Main Content -->

   <% end %>

app/views/shared/_fotter.html.erb
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Your Website 2020</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

app/views/shared/_header.html.erb
<!-- Topbar -->
<nav class="navbar fixed-top navbar-expand-lg  navbar-dark bg-primary">
    <%= link_to 'Helath Code', root_path, class: "navbar-brand" %>
<div class="text-white">
    <%= Date.current.strftime('%Y年 %m月') %>
</div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                データを登録する
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to '身体特徴', new_physicalfinding_overviews_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to '採血・採尿・画像検査', new_bloodurine_overviews_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to '受診歴', new_medicalcare_overviews_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to 'ワクチン接種歴', new_vaccine_overviews_path, class: "dropdown-item" %>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                登録データを見る
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to '身体特徴', physicalfinding_overview_path(current_user.id), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to '採血・採尿・画像検査', bloodurine_overview_path(current_user.id), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to '受診歴', medicalcare_overview_path(current_user.id), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to 'ワクチン接種歴', vaccine_overview_path(current_user.id), class: "dropdown-item" %>
                </div>
            </li>
        </ul>
        <% if user_signed_in? %>
                <%= link_to current_user.last_name  + current_user.first_name + "様", "#", class: "navbar-text mr-2"%>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "navbar-text mr-4"%>
            <% else %>          
                <%= link_to 'ログイン', new_user_session_path, class: "navbar-text mr-2" %>
                <%= link_to '新規登録', new_user_registration_path, class: "navbar-text mr-4" %>

        <% end %>
    </div>
</nav>